//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriHub.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class exped_nutricionalEntities : DbContext
    {
        public exped_nutricionalEntities()
            : base("name=exped_nutricionalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Consejo> Consejo { get; set; }
        public virtual DbSet<direccionUsuario> direccionUsuario { get; set; }
        public virtual DbSet<IngestaDiaria> IngestaDiaria { get; set; }
        public virtual DbSet<ListaCompras> ListaCompras { get; set; }
        public virtual DbSet<Nutricionista> Nutricionista { get; set; }
        public virtual DbSet<Nutriente> Nutriente { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<PacientePlanNutricional> PacientePlanNutricional { get; set; }
        public virtual DbSet<Padecimiento> Padecimiento { get; set; }
        public virtual DbSet<PadecimientoPaciente> PadecimientoPaciente { get; set; }
        public virtual DbSet<PlanNutricional> PlanNutricional { get; set; }
        public virtual DbSet<Progreso> Progreso { get; set; }
        public virtual DbSet<recibirConsejo> recibirConsejo { get; set; }
        public virtual DbSet<semana> semana { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tiempoComida> tiempoComida { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
